"""referral balance and ton bonus

Revision ID: c6222284fafe
Revises: f6f0dd6501a5
Create Date: 2026-07-15 10:17:33.679028
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6222284fafe'
down_revision = 'f6f0dd6501a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invites_balance', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('referral_ton_balance', sa.Float(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referral_ton_balance')
    op.drop_column('users', 'invites_balance')
    # ### end Alembic commands ###
