"""provably fair seeds

Revision ID: f6f0dd6501a5
Revises: 218bad086a8d
Create Date: 2026-07-12 13:57:13.703038
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6f0dd6501a5'
down_revision = '218bad086a8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('server_seed', sa.String(), nullable=True))
    op.add_column('users', sa.Column('server_seed_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('client_seed', sa.String(), nullable=True))
    op.add_column('users', sa.Column('nonce', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nonce')
    op.drop_column('users', 'client_seed')
    op.drop_column('users', 'server_seed_hash')
    op.drop_column('users', 'server_seed')
    # ### end Alembic commands ###
